export const SHOW_PRODUCT_CATALOG_INTENT = 'SHOW_PRODUCT_CATALOG';
export const VIEW_PRODUCT_INTENT = 'VIEW_PRODUCT';
export const WELCOME_MESSAGE_INTENT = 'WELCOME_MESSAGE';
export const ADD_TO_CART_INTENT = 'ADD_TO_CART';
export const VIEW_CART_INTENT = 'VIEW_CART';
